-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 22:53:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema contabilidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema contabilidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `contabilidad` DEFAULT CHARACTER SET utf8 ;
USE `contabilidad` ;

-- -----------------------------------------------------
-- Table `contabilidad`.`entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`entidad` (
  `id_entidad` INT NOT NULL,
  `nombre_entidad` TEXT(200) NULL,
  `direccion_entidad` TEXT(200) NULL,
  `fono1_entidad` INT NULL,
  `fono2_entidad` INT NULL,
  `ciudad_entidad` TEXT(200) NULL,
  PRIMARY KEY (`id_entidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`empleado` (
  `id_empleado` INT NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `id_entidad` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_empleado_entidad1_idx` (`id_entidad` ASC),
  CONSTRAINT `fk_empleado_entidad1`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `contabilidad`.`entidad` (`id_entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `ap_paterno_usuario` VARCHAR(45) NULL,
  `ap_materno_usuario` VARCHAR(45) NULL,
  `ci_usuario` INT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`periodo` (
  `id_periodo` INT NOT NULL,
  `anio_periodo` INT NULL,
  `fecha_inicio_periodo` DATE NULL,
  `fecha_cierre_periodo` DATE NULL,
  `entidad_id_entidad` INT NOT NULL,
  PRIMARY KEY (`id_periodo`),
  INDEX `fk_periodo_entidad1_idx` (`entidad_id_entidad` ASC),
  CONSTRAINT `fk_periodo_entidad1`
    FOREIGN KEY (`entidad_id_entidad`)
    REFERENCES `contabilidad`.`entidad` (`id_entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`tipo_transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`tipo_transaccion` (
  `id_tipo_transaccion` INT NOT NULL,
  `nombre_transaccion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_transaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`tipo_cambio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`tipo_cambio` (
  `id_tipo_cambio` INT NOT NULL,
  `monto` DOUBLE NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id_tipo_cambio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`tipo_pago` (
  `id_tipo_pago` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `descripcion_tipo_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`persona` (
  `id_persona` INT NOT NULL,
  `nombre_persona` VARCHAR(45) NULL,
  `ci_persona` INT NULL,
  `descripcion_persona` VARCHAR(45) NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`ficha` (
  `id_ficha` INT NOT NULL,
  `numero_partida_ficha` INT NULL,
  `fecha_ficha` DATE NULL,
  `tiempo_ficha` TIME NULL,
  `total_ficha` DOUBLE NULL,
  `total_debe_ficha` DOUBLE NULL,
  `total_haber_ficha` DOUBLE NULL,
  `id_tipo_transaccion` INT NOT NULL,
  `id_tipo_cambio` INT NOT NULL,
  `id_tipo_pago` INT NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_ficha`),
  INDEX `fk_ficha_tipo_transaccion1_idx` (`id_tipo_transaccion` ASC),
  INDEX `fk_ficha_tipo_cambio1_idx` (`id_tipo_cambio` ASC),
  INDEX `fk_ficha_tipo_pago1_idx` (`id_tipo_pago` ASC),
  INDEX `fk_ficha_persona1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_ficha_tipo_transaccion1`
    FOREIGN KEY (`id_tipo_transaccion`)
    REFERENCES `contabilidad`.`tipo_transaccion` (`id_tipo_transaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_tipo_cambio1`
    FOREIGN KEY (`id_tipo_cambio`)
    REFERENCES `contabilidad`.`tipo_cambio` (`id_tipo_cambio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_tipo_pago1`
    FOREIGN KEY (`id_tipo_pago`)
    REFERENCES `contabilidad`.`tipo_pago` (`id_tipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `contabilidad`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`empleado_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`empleado_usuario` (
  `id_empleado_usuario` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `user` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empleado_usuario`),
  INDEX `fk_empleado_usuario_empleado1_idx` (`id_empleado` ASC),
  INDEX `fk_empleado_usuario_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_empleado_usuario_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `contabilidad`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_usuario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `contabilidad`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`empleado_ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`empleado_ficha` (
  `id_empleado_ficha` INT NOT NULL,
  `descripcion_empleado` VARCHAR(45) NULL,
  `id_ficha` INT NOT NULL,
  `id_empleado_usuario` INT NOT NULL,
  PRIMARY KEY (`id_empleado_ficha`),
  INDEX `fk_empleado_ficha_ficha1_idx` (`id_ficha` ASC),
  INDEX `fk_empleado_ficha_empleado_usuario1_idx` (`id_empleado_usuario` ASC),
  CONSTRAINT `fk_empleado_ficha_ficha1`
    FOREIGN KEY (`id_ficha`)
    REFERENCES `contabilidad`.`ficha` (`id_ficha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_ficha_empleado_usuario1`
    FOREIGN KEY (`id_empleado_usuario`)
    REFERENCES `contabilidad`.`empleado_usuario` (`id_empleado_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`documento_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`documento_extra` (
  `id_documento_extra` INT NOT NULL,
  `codigo_documento` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `id_ficha` INT NOT NULL,
  PRIMARY KEY (`id_documento_extra`),
  INDEX `fk_documento_extra_ficha1_idx` (`id_ficha` ASC),
  CONSTRAINT `fk_documento_extra_ficha1`
    FOREIGN KEY (`id_ficha`)
    REFERENCES `contabilidad`.`ficha` (`id_ficha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`clase` (
  `id_clase` INT NOT NULL,
  `nombre_clase` TEXT(300) NULL,
  `estado_clase` VARCHAR(45) NULL,
  `fecha_registro_clase` DATE NULL,
  `fecha_modifico_clase` DATE NULL,
  PRIMARY KEY (`id_clase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`grupo` (
  `id_grupo` INT NOT NULL,
  `nombre_grupo` TEXT(300) NULL,
  `estado_grupo` VARCHAR(45) NULL,
  `fecha_registro_grupo` DATE NULL,
  `fecha_modifico_grupo` DATE NULL,
  `id_clase` INT NOT NULL,
  PRIMARY KEY (`id_grupo`),
  INDEX `fk_grupo_clase1_idx` (`id_clase` ASC),
  CONSTRAINT `fk_grupo_clase1`
    FOREIGN KEY (`id_clase`)
    REFERENCES `contabilidad`.`clase` (`id_clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`cuenta` (
  `id_cuenta` INT NOT NULL,
  `nombre_cuenta` TEXT(300) NULL,
  `estado_cuenta` VARCHAR(45) NULL,
  `fecha_registro_cuenta` DATE NULL,
  `fecha_modifico_cuenta` DATE NULL,
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_cuenta`),
  INDEX `fk_cuenta_grupo1_idx` (`id_grupo` ASC),
  CONSTRAINT `fk_cuenta_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `contabilidad`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`subcuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`subcuenta` (
  `id_subcuenta` INT NOT NULL,
  `nombre_subcuenta` TEXT(300) NULL,
  `estado_subcuenta` VARCHAR(45) NULL,
  `fecha_registro_subcuenta` DATE NULL,
  `fecha_modifico_subcuenta` DATE NULL,
  `id_cuenta` INT NOT NULL,
  PRIMARY KEY (`id_subcuenta`),
  INDEX `fk_subcuenta_cuenta1_idx` (`id_cuenta` ASC),
  CONSTRAINT `fk_subcuenta_cuenta1`
    FOREIGN KEY (`id_cuenta`)
    REFERENCES `contabilidad`.`cuenta` (`id_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`asiento` (
  `id_asiento` INT NOT NULL,
  `glosa_asiento` TEXT(300) NULL,
  `cantidad_asiento` INT NULL,
  `monto_asiento` DOUBLE NULL,
  `debe_asiento` DOUBLE NULL,
  `haber_asiento` DOUBLE NULL,
  `ficha_id_ficha` INT NOT NULL,
  `id_subcuenta` INT NOT NULL,
  PRIMARY KEY (`id_asiento`),
  INDEX `fk_asiento_ficha1_idx` (`ficha_id_ficha` ASC),
  INDEX `fk_asiento_subcuenta1_idx` (`id_subcuenta` ASC),
  CONSTRAINT `fk_asiento_ficha1`
    FOREIGN KEY (`ficha_id_ficha`)
    REFERENCES `contabilidad`.`ficha` (`id_ficha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asiento_subcuenta1`
    FOREIGN KEY (`id_subcuenta`)
    REFERENCES `contabilidad`.`subcuenta` (`id_subcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`amortizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`amortizacion` (
  `id_amortizacion` INT NOT NULL,
  `detalle_amortizacion` TEXT(300) NULL,
  `monto_amortizacion` DOUBLE NULL,
  `interes_amortizacion` DOUBLE NULL,
  `tiempo_amortizacion` INT NULL,
  PRIMARY KEY (`id_amortizacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`asiento_amortizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`asiento_amortizacion` (
  `id_asiento_amortizacion` INT NOT NULL,
  `periodo_amortizacion` INT NULL,
  `capital_inicial` DOUBLE NULL,
  `pago_interes` DOUBLE NULL,
  `amortizacion` DOUBLE NULL,
  `cuota` DOUBLE NULL,
  `saldo_final` DOUBLE NULL,
  `fecha_amortizacion` DATE NULL,
  `id_amortizacion` INT NOT NULL,
  `id_asiento` INT NOT NULL,
  PRIMARY KEY (`id_asiento_amortizacion`),
  INDEX `fk_asiento_amortizacion_amortizacion1_idx` (`id_amortizacion` ASC),
  INDEX `fk_asiento_amortizacion_asiento1_idx` (`id_asiento` ASC),
  CONSTRAINT `fk_asiento_amortizacion_amortizacion1`
    FOREIGN KEY (`id_amortizacion`)
    REFERENCES `contabilidad`.`amortizacion` (`id_amortizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asiento_amortizacion_asiento1`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `contabilidad`.`asiento` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`subcuenta_amortizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`subcuenta_amortizacion` (
  `id_subcuenta_amortizacion` INT NOT NULL,
  `fecha_subcuenta_amortizacion` DATE NULL,
  `id_amortizacion` INT NOT NULL,
  `id_subcuenta` INT NOT NULL,
  PRIMARY KEY (`id_subcuenta_amortizacion`),
  INDEX `fk_subcuenta_amortizacion_amortizacion1_idx` (`id_amortizacion` ASC),
  INDEX `fk_subcuenta_amortizacion_subcuenta1_idx` (`id_subcuenta` ASC),
  CONSTRAINT `fk_subcuenta_amortizacion_amortizacion1`
    FOREIGN KEY (`id_amortizacion`)
    REFERENCES `contabilidad`.`amortizacion` (`id_amortizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subcuenta_amortizacion_subcuenta1`
    FOREIGN KEY (`id_subcuenta`)
    REFERENCES `contabilidad`.`subcuenta` (`id_subcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`depreciacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`depreciacion` (
  `id_depreciacion` INT NOT NULL,
  `bien` VARCHAR(45) NULL,
  `vida_util` INT NULL,
  PRIMARY KEY (`id_depreciacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`asiento_deperciacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`asiento_deperciacion` (
  `id_asiento_deperciacion` INT NOT NULL,
  `periodo_depreciacion` INT NULL,
  `valor_original` DOUBLE NULL,
  `depreciacion` DOUBLE NULL,
  `acumulado` DOUBLE NULL,
  `valor_residual` DOUBLE NULL,
  `fecha_depreciacion` DATE NULL,
  `id_depreciacion` INT NOT NULL,
  `id_asiento` INT NOT NULL,
  PRIMARY KEY (`id_asiento_deperciacion`),
  INDEX `fk_asiento_deperciacion_depreciacion1_idx` (`id_depreciacion` ASC),
  INDEX `fk_asiento_deperciacion_asiento1_idx` (`id_asiento` ASC),
  CONSTRAINT `fk_asiento_deperciacion_depreciacion1`
    FOREIGN KEY (`id_depreciacion`)
    REFERENCES `contabilidad`.`depreciacion` (`id_depreciacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asiento_deperciacion_asiento1`
    FOREIGN KEY (`id_asiento`)
    REFERENCES `contabilidad`.`asiento` (`id_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contabilidad`.`subcuenta_depreciacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contabilidad`.`subcuenta_depreciacion` (
  `id_subcuenta_depreciacion` INT NOT NULL,
  `fecha_subcuenta_depreciacion` DATE NULL,
  `id_depreciacion` INT NOT NULL,
  `id_subcuenta` INT NOT NULL,
  PRIMARY KEY (`id_subcuenta_depreciacion`),
  INDEX `fk_subcuenta_depreciacion_depreciacion1_idx` (`id_depreciacion` ASC),
  INDEX `fk_subcuenta_depreciacion_subcuenta1_idx` (`id_subcuenta` ASC),
  CONSTRAINT `fk_subcuenta_depreciacion_depreciacion1`
    FOREIGN KEY (`id_depreciacion`)
    REFERENCES `contabilidad`.`depreciacion` (`id_depreciacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subcuenta_depreciacion_subcuenta1`
    FOREIGN KEY (`id_subcuenta`)
    REFERENCES `contabilidad`.`subcuenta` (`id_subcuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
